name: 'Build and test action'
description: 'Build and test something'
inputs:
  bt-param:  # id of input
    description: 'Build and test params'
    required: true
  artifact-name:  # id of input
    description: 'Artifact name'
    required: true
runs:
  using: "composite"
  steps:
    if: [runs-ons == 'windows-2019']
    - run: dotnet test ${{ inputs.bt-param }} -o "${{github.workspace}}/artifactTests/${{ inputs.artifact-name }}"
      shell: pwsh
    if: [runs-ons == 'ubuntu-latest']
    - run: xvfb dotnet test ${{ inputs.bt-param }} -o "${{github.workspace}}/artifactTests/${{ inputs.artifact-name }}"
      shell: pwsh